version: '3.4'

services:
  hangfire-sample-web:
    image: hangfire-sample-web
    container_name: hangfire-sample-web
    build:
      context: .
      dockerfile: src/HangfireSample.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
    depends_on:
      - hangfire-sample-db
  hangfire-sample-db:
    container_name: hangfire-sample-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
